version: '2'
services:
    webdash_cw-mysql:
        container_name: webdash_cw-mysql
        image: mysql:5.7.13
        # volumes:
        #     - ~/volumes/jhipster/WebDash_CW/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=webdash_cw
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
